{% set name = "netgen" %}
{% set version = "6.2.1811.b0" %}
{% set sha256 = "fc44bc281958e7255b961d0c31569a3dc575ebe4080b1fa35af79afb4adf4eff" %}


package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: netgen_v{{ version }}.tar.gz
    # url: https://github.com/NGSolve/netgen/archive/v{{ version }}.tar.gz
    url: https://github.com/NGSolve/netgen/archive/86488d033e797976cb4593e1cd3d6e6b2380bbc4.tar.gz
    sha256: {{ sha256 }}
    patches:
        - salome.patch  # [unix]
        - salome_win.patch  # [win]
build:
    number: 1000
    skip: True  # [py27]

requirements:
    build:
        - {{ compiler('cxx') }}
        - {{ cdt('mesa-libgl-devel') }}  # [linux]
        - {{ cdt('mesa-dri-drivers') }}  # [linux]
        - ninja
    host:
        - cmake
        - occt
        - python
        - pybind11
    run:
        - occt
        - python

test:
    imports:
        - netgen

about:
    home: https://sourceforge.net/projects/netgen-mesher/
    license: LGPL2.1
    license_family: LGPL
    summary: this is netgen
    description: NETGEN is an automatic 3d tetrahedral mesh generator.
                 It accepts input from constructive solid geometry (CSG) or boundary representation (BRep) from
                 STL file format. The connection to a geometry kernel allows the handling of IGES and STEP files.
                 NETGEN contains modules for mesh optimization and hierarchical mesh refinement.
                 Netgen is open source based on the LGPL license. It is available for Unix/Linux and Windows.
    doc_url: http://www.hpfem.jku.at/netgen/
    dev_url: https://sourceforge.net/projects/netgen-mesher/

extra:
    recipe-maintainers:
        - looooo
