travis:
  secure:
    BINSTAR_TOKEN: PsXpzUYqN03+1ROgD5lrYz3pRMBhS85P+6sSyT8MAX+I4IT1gV9zxphb9PRhhFYccIkqJYIkjAjOM7jWGWIp0lug1mZBWxK8Od+UVfvPG+hTNKlmz8iNoGpvr9A76Cz3habDhhVBxIRWX0OZnhVlMCwyB5NfFxEj0WLew4kfMpmeqDbTzS5gBEyTk1RcObC13N50sbYF3JzxbfGAfcaSoj8QPY+s0DUwXPGiTcfgsqbRjHnXavDQvlAWXnUXxKLQ3pMwkeR0DCaEMGK3wCs7SDDpqsv968/B46ea7Sdkydq0Syp4/yz5u01hJKhDBl5Gr5Y/QHJAw91dxl0ju8wqHeqmJh1sDmtmnHzGrxY5OmpjZYPiXXJNwkmtFw9XIaHDYR612Cg9a62ihK+OCqQYq5P9eD2ZTubyBQcvwvnEAhJ3ABo0UjbKDBLCVZXXhS+FIlAoGcW9rlhxBySFlEqa0LKt55eAc+9887gRNpjYyMRq3isj7+Km5aBOnlUGo9lD2KQmXYZIjeKlvBVZcWbYm/e+zBADDcmK+pJMz157oasvpir6DG61AUpj2NSBRJXqC+vNtkDOc6BmJhCs4uMo7IVKXNob6/EAOKr3Mwqrae78oL4/kQmjOhhCGD4jjL8L3VLlkRX+6xgOIo2hTqgTcXJqiSui0vkdHdRtnA6nb3s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
