appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: su3VXEN9PE7Gl/Nyhk3QARgpWlpdr1XF6MGaZDFAV61yZ9LocKja97cFZ9jf2C+OyfEoDwDX7cLSsAl179JudmOdpPx2A5jNV9Jz7xOkR96plmEsJtHtXO3tFSi6qgjFkCriA3AKtODczOywk6AeU5tbq8RDCu1GxiHLTK0k0q6sRImaN0zJLmMV266q0gAs9lNU5psLqp7VEMCNslhyGc7Q19CdmXESy760Iqmmt+eU2bAW/dYMjdyrx0eZQ/ZGz/lZMxC1Wvps9f+H1EO+QNxtOyKk4cNSFwvX5k5YzQUvj4ZBOKwIJupmq38NF8kDF66260Ch+Z04JJOSS8mRdO19EJSpqo9WacwFfOWgPm0q70yvlL9EH/oVl6/ox3UGU6/JTmdtzMMbQgvLljNo3+1CNtGbBF7tjsxF57bYLsqboFp507FL24/Brn2yaoDjut7w3eYWPTNNcXubhef5El7JiYB4ZNvZXkIOloN1I0d1aQKAzus6EDRL3HeqldEbWRWF54cs/v9Q7OddMrdr4z1OpvWTIkSaRpts+dOD8w0n4fK9S7A48DYHlZpv4FE1Z9SVviduVrcP5HVLqa2AtVV2koqI3+DSEWOITifVsuFL89K3BMDJy3DknJ3+/Xqss+GnnooQjzbf8WjilcxvfBytxFVb2eYmNLrEkYgy2Ok=}
